name: flutter_gauge
description: A little widget that given an Observable gives you an updated FlutterGauge.
version: 1.0.8
author: alitorki2651@gmail.com
homepage: https://github.com/alitorki2651/flutter_gauge

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
